#!/bin/sh
PREREQS=""
case $1 in
        prereqs) echo "${PREREQS}"; exit 0;;
esac

ID=252

. /scripts/functions

ID=$( sed "s#.*:p\(.*\):usb0.10.*#\1#" /proc/cmdline )
HEXID=$( echo $ID | awk '{printf("%02x\n",$1)}' )

modprobe dwc2
modprobe libcomposite
mount -t configfs none /sys/kernel/config/
cd /sys/kernel/config/usb_gadget/
mkdir ClusterCTRL && cd ClusterCTRL
echo "0x3171" > idVendor
echo "0x0020" > idProduct 
echo "0x0100" > bcdDevice
echo "0x0200" > bcdUSB
echo "0xEF" > bDeviceClass
echo "0x02" > bDeviceSubClass
echo "0x01" > bDeviceProtocol

mkdir -p strings/0x409
echo "$ID" > strings/0x409/serialnumber
echo "8086 Consultancy" > strings/0x409/manufacturer
echo "ClusterCTRL-usbboot" > strings/0x409/product

mkdir -p functions/acm.usb0
mkdir -p functions/acm.usb1
mkdir -p functions/ncm.usb0

# Assign MAC addresses to the NCM interface
echo "00:22:82:ff:fe:$HEXID" > functions/ncm.usb0/host_addr
echo "00:22:82:ff:ff:$HEXID" > functions/ncm.usb0/dev_addr

mkdir -p configs/c.1
echo "250" > configs/c.1/MaxPower

# Link the interfaces to the configuration
ln -s functions/ncm.usb0 configs/c.1/
ln -s functions/acm.usb0 configs/c.1/
ln -s functions/acm.usb1 configs/c.1/

udevadm settle -t 5 || :
ls /sys/class/udc/ > UDC

# Create the VLAN interface for NFSROOT
ip link add link usb0 name usb0.10 type vlan id 10
ip link set dev usb0.10 mtu 1496
ip link set dev usb0 up
ip link set dev usb0.10 up
if [ -f /bin/ifmetric ]; then
	ifmetric usb0.10 1100
fi

exit 0
